### ISSUE TITLE
Bombproofify build against switching compilers

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#96]
As of PR #93 the README states:

> Sometimes when switching between compilers, CMake doesn't seem to fully reset on the first attempt of the build. It is not clear why this is the case, but the issue seems to be resolved by running the `spack install` command again.

It would be nice to not have this problem.

**Comment by cmacmackin** [comment]
I believe I have identified the source of this issue. I think it was related to the existence of the [filesystem view](https://spack.readthedocs.io/en/latest/environments.html#filesystem-views) on the CMAKE_PREFIX_PATH, causing CMake to find a lingering version of MKL rather than FFTW as it should have. I'm going to change the configurations so there isn't a filesystem view on CMAKE_PREFIX_PATH (or any other environment variables, for that matter).

**Comment by jwscook** [comment]
Might this change have side effects?

**Comment by cmacmackin** [comment]
Not really, no. It somewhat changes one of the ways you can build NESO (using the filesystem view rather than `spack install`), but that wasn't a good way to go about building anyway.
